baseURL = 'https://www.ashistry.eu'
languageCode = 'en-us'
title = 'Ashistry'
theme='ashistrytheme'
description='A blog about tech, FOSS, art, and everything I like!'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    style = "modus-vivendi"

    [menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[menus.main]] 
  name ='RSS'
  url = '/index.xml'
  weight= 40

  [[menus.main]] 
  name='Contact'
  url = 'mailto:ashistry@proton.me'
  weight=50

rssLimit = 25